name: Build mozjs

on:
  workflow_dispatch:
    inputs:
      mozjs-tag:
        description: "mozjs version tag to be used"
        required: true
        type: string

jobs:
  riscv64-cross-compile:
    runs-on: self-hosted
    container: ghcr.io/huancheng-trili/cross-riscv64gc-unknown-linux-musl:5f9a19d
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.82.0
        with:
          targets: riscv64gc-unknown-linux-musl
      - name: Dummy
        shell: bash
        run: uname -a
      - name: Build
        shell: bash
        run: ./run.sh ${{ inputs.mozjs-tag }}
      - name: Upload artifact
        if: ${{ matrix.features != 'debugmozjs' }}
        uses: actions/upload-artifact@v4
        with:
          path: ./mozjs/target/libmozjs-riscv64gc-unknown-linux-musl.tar.gz
          name: libmozjs-riscv64gc-unknown-linux-musl.tar.gz
  publish-release:
    name: Check version and publish release
    runs-on: ubuntu-latest
    needs: ["riscv64-cross-compile"]
    if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Publish release if tag doesn't exist
        id: check-tag
        run: |
          RELEASE_TAG=${{ inputs.mozjs-tag }}
          gh release create ${RELEASE_TAG} ./*.tar.gz
          echo "RELEASE_TAG=${RELEASE_TAG}" >> ${GITHUB_OUTPUT}
    outputs:
      release-tag: ${{ steps.check-tag.outputs.RELEASE_TAG }}
